name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y k6  

      - name: Load Test and Stress Test
        run: k6 run load_test.js
        
      - name: Stress Test
        run: k6 run stress_test.js
