name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g k6

      - name: Run linter
        run: pylint src/

      - name: Run security check
        run: bandit -r src/

      - name: Run load test
        run: k6 run load_test.js

      - name: Run stress test
        run: k6 run stress_test.js

  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run security check
        run: bandit -r src/

  build:
    runs-on: ubuntu-latest

    needs: [lint, security-check]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t k1rif13/voting-app:latest .

      - name: Log into Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push k1rif13/voting-app:latest
